# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Manager
    ports:
      - 5432:5432
    networks:
      - sharednetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    networks:
      - sharednetwork

networks:
  sharednetwork:
    driver: bridge